[build]
  functions = "netlify/functions"

[build.environment]
  GO_VERSION = "1.22.6"

# Optional: include static assets used by handlers (placeholders, etc.)
[functions]
  included_files = ["assets/**", "public/**", "static/**"]

# Route all API requests to the serverless function "api"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
